#
# Module manifest for module 'Get-PackageUpdates'
#
# Generated by: JanJoris
#
# Generated on: 2/27/2017
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Get-PackageUpdates.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.3'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID = '37f248c9-6871-429b-8d57-173f6f8359c4'

    # Author of this module
    Author = 'JanJoris'

    # Company or vendor of this module
    CompanyName = 'herebedragons.io'

    # Copyright statement for this module
    Copyright = '(c) 2017 JanJoris. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Print updates for chocolatey and the PSGallery whenever you start a PowerShell session'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Write-PackageUpdates','Save-PackageUpdates','Get-PackageUpdates')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('chocolatey', 'PSGallery', 'updates', 'update', 'package')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/JanJoris/Get-PackageUpdates/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/JanJoris/Get-PackageUpdates'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
